# -*- coding: utf-8 -*-
"""symmetric_eigen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-xducC5L4Wh3seA3pj5K54LtBin6CGY
"""

import numpy as np

def generate_invertible_matrix(n):
    # Generate a random n x n matrix with integer entries
    random_matrix = np.random.randint(low=1, high=10, size=(n, n))

    # Check if the matrix is invertible
    while np.linalg.matrix_rank(random_matrix) < n:
        random_matrix = np.random.randint(low=1, high=10, size=(n, n))

    return random_matrix

def generate_symmetric_invertible_matrix(n):
    # Step 1: Generate a random invertible matrix
    invertible_matrix = generate_invertible_matrix(n)

    # Step 2: Create a symmetric matrix from the invertible matrix
    symmetric_matrix = np.dot(invertible_matrix, invertible_matrix.T)

    return symmetric_matrix

# Take the dimension 'n' as input
n = int(input("Enter the dimension 'n' of the matrix: "))

# Generate the symmetric invertible matrix
symmetric_invertible_matrix = generate_symmetric_invertible_matrix(n)

print("Symmetric Invertible Matrix:")
print(symmetric_invertible_matrix)

eigen_values, eigen_vectors = np.linalg.eig(symmetric_invertible_matrix)

print("\nEigen Values:")
print(eigen_values)
print("\nEigen Vectors:")
print(eigen_vectors)

diag_lambda = np.diag(eigen_values)
re_1 = eigen_vectors.dot(diag_lambda)
reconstructed_symmetric_invertible_matrix = re_1.dot(np.linalg.inv(eigen_vectors)) # A = V.diag(lambda).V_inv
print("\nReconstructed Symmetric Invertible Matrix:")
print(reconstructed_symmetric_invertible_matrix)

are_matrices_equal = np.allclose(symmetric_invertible_matrix, reconstructed_symmetric_invertible_matrix)

if are_matrices_equal:
    print("\nThe matrices are equal.")
else:
    print("\nThe matrices are not equal.")
